const assert=require('node:assert/strict');
const {validateCv}=require('../backend/dist/lib/cv.js');
const {validateEnvironment}=require('../backend/dist/lib/environment.js');
const {mergeGroups}=require('../backend/dist/routes/people.js');
const {buildImportPlan}=require('../backend/dist/routes/importData.js');
const file=(data,mimeType='application/pdf')=>({filename:'cv.pdf',mimeType,dataBase64:Buffer.from(data).toString('base64')});
assert.equal(validateCv(file('%PDF-1.7\ncontent')).mime,'application/pdf');
assert.throws(()=>validateCv(file('not a PDF')));
assert.throws(()=>validateCv(file('%PDF-1.7','image/png')));
assert.throws(()=>validateCv({filename:'bad',mimeType:'application/pdf',dataBase64:'AAAA==='}));
assert.throws(()=>validateCv(file(Buffer.alloc(15*1024*1024+1))));
assert.throws(()=>validateEnvironment({DATABASE_URL:'test',JWT_SECRET:'short'}));
assert.throws(()=>validateEnvironment({DATABASE_URL:'test',JWT_SECRET:'x'.repeat(32),NODE_ENV:'production',FRONTEND_URL:'*'}));
assert.doesNotThrow(()=>validateEnvironment({DATABASE_URL:'test',JWT_SECRET:'x'.repeat(32),NODE_ENV:'production',FRONTEND_URL:'https://hr.example'}));
let groups=mergeGroups([{id:1,name:'David',phone:'054-1234567'},{id:2,name:'דוד',phone:'+972541234567'}]);
assert.equal(groups.length,1);assert.equal(groups[0].name,'דוד');assert.equal(groups[0].conflict,false);
groups=mergeGroups([{id:1,name:'Same',phone:'0541234567',national_id:'111'},{id:2,name:'Same',phone:'0541234567',national_id:'222'}]);
assert.equal(groups[0].conflict,true);
assert.equal(mergeGroups([{id:1,name:'Same'},{id:2,name:'Same'}]).length,0);
const state={clients:[],jobs:[],people:[{id:1,name:'Legacy',phone:'0501234567'}],applications:[{id:1,person_id:1,source:'excel',import_key:null,job_id:null,role:'A',summary_text:'same'},{id:2,person_id:1,source:'excel',import_key:null,job_id:null,role:'A',summary_text:'same'}]};
const p=buildImportPlan({candidates:[{name:'Legacy',phone:'0501234567',role:'A',summaryText:'same',importKey:'legacy:1'}]},state);
assert.equal(p.issues.length,1);assert.equal(p.plan.length,0);
const fs=require('node:fs');
const path=require('node:path');const web=fs.existsSync(path.join(__dirname,'../web'))?'../web':'../frontend';
const built=fs.readFileSync(path.join(__dirname,web,'index.html'),'utf8');
assert.ok(!/<script>/.test(built));assert.ok(!/\son(?:click|change|submit|input|keydown)=/.test(built));
const code=fs.readFileSync(path.join(__dirname,web,'app.js'),'utf8');
assert.ok(!/localStorage\.(?:setItem|getItem)\(['"]hr_token/.test(code));
console.log('PASS: file signatures/size/base64, environment, phone normalization and merge conflicts, ambiguous legacy import, CSP-compatible frontend');
